name: Test Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-python:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-gi \
          python3-gi-cairo \
          gir1.2-gtk-4.0 \
          libgirepository1.0-dev \
          gcc \
          libcairo2-dev \
          pkg-config \
          python3-dev \
          gir1.2-gtk-3.0 \
          ffmpeg
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Syntax check
      run: |
        python -m py_compile whisper_transcriber.py
    
    - name: Import test
      run: |
        python -c "
        import sys
        sys.argv = ['whisper_transcriber.py']
        try:
            import whisper_transcriber
            print('✓ Import successful')
        except ImportError as e:
            print(f'✗ Import failed: {e}')
            sys.exit(1)
        except Exception as e:
            print(f'✓ Import successful (runtime error expected in CI: {e})')
        "
